// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjkkST6JQ4UcLO59sfveFUMjL5JiN5L4',
    appId: '1:351335683511:web:458dd15f8285af7a030432',
    messagingSenderId: '351335683511',
    projectId: 'dartfri',
    authDomain: 'dartfri.firebaseapp.com',
    storageBucket: 'dartfri.appspot.com',
    measurementId: 'G-3EG1S7D223',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3rZLJ3_q74Akc0iT-HWqQ6hUJL7Ge-w',
    appId: '1:351335683511:android:5f3798b976b41dbc030432',
    messagingSenderId: '351335683511',
    projectId: 'dartfri',
    storageBucket: 'dartfri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrT_0JboEWqi1um0CHkVN1W6b1_hrIfY',
    appId: '1:351335683511:ios:ae6083dffa00a1a5030432',
    messagingSenderId: '351335683511',
    projectId: 'dartfri',
    storageBucket: 'dartfri.appspot.com',
    androidClientId: '351335683511-6u2ov24hvnmhqhtcc5tr9vvtt8dlc35i.apps.googleusercontent.com',
    iosClientId: '351335683511-sjp964evc0vk9aa4qke6hdjng94j8p5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartfri',
  );
}
